name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-eks-cost-optimized/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_OIDC }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=terraform-eks-cost-optimized init

      - name: Terraform Apply (Aprovação Manual)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: ${{ secrets.APPROVERS }}
          instructions: 'Aprovar para aplicar mudanças em produção.'

      - name: Terraform Apply
        if: ${{ steps.manual-approval.outputs.approved == 'true' }}
        run: terraform -chdir=terraform-eks-cost-optimized apply -auto-approve

      - name: Notificação Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
