name: Terraform Apply


on:
  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_OIDC }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=terraform-eks-cost-optimized init

      - name: Terraform Apply (Infra AWS)
        run: terraform -chdir=terraform-eks-cost-optimized apply -auto-approve -target=module.eks

      - name: Configure kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-east-1 --name eks-lab

      - name: Terraform Apply (K8s/Helm)
        run: terraform -chdir=terraform-eks-cost-optimized apply -auto-approve

      - name: Notificação Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
          text: |
            :rocket: *Status do Deploy Terraform*
            O workflow terminou com status: *${{ job.status }}*
            Repositório: ${{ github.repository }}
            Autor: ${{ github.actor }}
            Commit: ${{ github.sha }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
